/*

  ******************************************************************************
TODO: add license
  ******************************************************************************
  */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "stm32l1xx_hal.h"
#include "adc.h"
#include "gpio.h"
#include "pwm.h"
#include "encoder.h"
#include "motion_sensor.h"
#include "colorwheel.h"
#include "settings.h"

/* Private variables ---------------------------------------------------------*/

int8_t encoder_rotation = 0;  /* flag for encoder rotation (1=cw ; -1=ccw ; 0=nothing) */

uint8_t encoder_button_pressed = 0;  /* flag for encoder button press */

uint16_t colorwheel_angle = 0;

uint8_t color_r = 0;
uint8_t color_g = 0;
uint8_t color_b = 0;

uint8_t brightness = 0;

uint8_t test = 0;

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);

void rotation_cb(uint8_t direction);
void button_cb(void);

int main(void) {

	/* MCU Configuration----------------------------------------------------------*/

	/* Reset of all peripherals, Initializes the Flash interface and the Systick. */
	HAL_Init();

	/* Configure the system clock */
	SystemClock_Config();

	settings_init();
	color_r = config_bank.r;
	color_g = config_bank.g;
	color_b = config_bank.b;
	brightness = config_bank.brightness;
	/* Initialize all configured peripherals */
	MX_GPIO_Init();
	MX_ADC_Init();

	/* initilaize pwm for controlling the LED strip */
	pwm_init();
	pwm_start();

	encoder_init();
	encoder_set_rotation_callback(rotation_cb);
	encoder_set_button_callback(button_cb);
	encoder_start();

	colorwheel_set_brightness(brightness, &color_r, &color_g, &color_b);
	pwm_set_dutycyle(PWM_CH_R, (float)color_r /255.0f);
	pwm_set_dutycyle(PWM_CH_G, (float)color_g /255.0f);
	pwm_set_dutycyle(PWM_CH_B, (float)color_b /255.0f);
	brightness = 100;

	/* Infinite loop */
	while (1) {

		if(encoder_rotation==1)
		{
			encoder_rotation = 0;
			if(colorwheel_angle>350)
			{
				colorwheel_angle = 0;
			}
			colorwheel_angle +=10;
			colorwheel_get_rgb(colorwheel_angle, &color_r, &color_g, &color_b);
			colorwheel_set_brightness(brightness, &color_r, &color_g, &color_b);
			pwm_set_dutycyle(PWM_CH_R, (float)color_r /255.0f);
			pwm_set_dutycyle(PWM_CH_G, (float)color_g /255.0f);
			pwm_set_dutycyle(PWM_CH_B, (float)color_b /255.0f);


		}
		else if (encoder_rotation==-1)
		{
			encoder_rotation = 0;
			if(colorwheel_angle<10)
			{
				colorwheel_angle = 360;
			}
			colorwheel_angle -=10;
			colorwheel_get_rgb(colorwheel_angle, &color_r, &color_g, &color_b);
			colorwheel_set_brightness(brightness, &color_r, &color_g, &color_b);
			pwm_set_dutycyle(PWM_CH_R, (float)color_r /255.0f);
			pwm_set_dutycyle(PWM_CH_G, (float)color_g /255.0f);
			pwm_set_dutycyle(PWM_CH_B, (float)color_b /255.0f);
		}

		if(encoder_button_pressed==1)
		{
			encoder_button_pressed = 0;
			pwm_set_dutycyle(PWM_CH_G, 0.3);
			HAL_Delay(100);
			pwm_set_dutycyle(PWM_CH_G, 0.0);
		}

		if(test==1)
		{
			test = 0;
			settings_save();
		}
	}

}

/** System Clock Configuration (generated by CubeMX)
*/
void SystemClock_Config(void)
{

  RCC_OscInitTypeDef RCC_OscInitStruct;
  RCC_ClkInitTypeDef RCC_ClkInitStruct;

    /**Configure the main internal regulator output voltage 
    */
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    /**Initializes the CPU, AHB and APB busses clocks 
    */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = 16;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL3;
  RCC_OscInitStruct.PLL.PLLDIV = RCC_PLL_DIV4;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    _Error_Handler(__FILE__, __LINE__);
  }

    /**Initializes the CPU, AHB and APB busses clocks 
    */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK)
  {
    _Error_Handler(__FILE__, __LINE__);
  }

    /**Configure the Systick interrupt time 
    */
  HAL_SYSTICK_Config(HAL_RCC_GetHCLKFreq()/1000);

    /**Configure the Systick 
    */
  HAL_SYSTICK_CLKSourceConfig(SYSTICK_CLKSOURCE_HCLK);

  /* SysTick_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(SysTick_IRQn, 0, 0);
}


/**
  * @brief  This function is executed in case of error occurrence.
  * @param  None
  * @retval None
  */
void _Error_Handler(char * file, int line)
{
  /* User can add his own implementation to report the HAL error return state */
  while(1) 
  {
  }
}



void rotation_cb(uint8_t direction)
{
	if(direction)
	{
		encoder_rotation = 1;
	}else{
		encoder_rotation = -1;
	}
}

void button_cb(void)
{
	encoder_button_pressed = 1;
}



/* Interrupt callback for GPIO interrupts */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
	if(GPIO_Pin == ENCODER_BTN_PIN)
	{
		encoder_button_interrupt_handler();
	}

	if(GPIO_Pin == MOTION_SENSOR_GPIO_PIN)
	{
		motion_sensor_interrupt_handler();
	}
}
